// Stable admin routes helper (NOT autogenerated)
// Use these instead of placing custom code under resources/js/routes (Wayfinder overwrites that directory).

export function adminPath(...segments: string[]): string {
    const base = '/dashboard/admin';
    if (!segments.length) return base;
    return [base, ...segments.map((s) => s.replace(/^\/+|\/+$/g, ''))].join(
        '/',
    );
}

export const adminRoutes = {
    index: () => adminPath(),
    rolesPermissions: () => adminPath('roles-permissions'),
};

export type AdminRouteKey = keyof typeof adminRoutes;
